/**
 * Stable, machine-readable error codes for the frontend to switch on.
 * These never change even if `message` text gets reworded or translated —
 * the frontend should key its UI logic off `code`, not off `message`.
 */
const ERROR_CODES = {
  // 400 — validation / bad input
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',

  // 401 — auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_MISSING: 'TOKEN_MISSING',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  USER_NO_LONGER_EXISTS: 'USER_NO_LONGER_EXISTS',

  // 403 — permissions
  ROLE_NOT_ALLOWED: 'ROLE_NOT_ALLOWED',
  NOT_EVENT_OWNER: 'NOT_EVENT_OWNER',
  NOT_REVIEW_OWNER: 'NOT_REVIEW_OWNER',

  // 404
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  ATTENDANCE_NOT_FOUND: 'ATTENDANCE_NOT_FOUND',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',

  // 409 — conflicts
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  EVENT_FULL: 'EVENT_FULL',
  ALREADY_JOINED: 'ALREADY_JOINED',
  NOT_ATTENDED: 'NOT_ATTENDED',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',

  // 500
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

module.exports = ERROR_CODES;